### ISSUE TITLE
Error during terraform apply

### ISSUE THREAD

**Issue by Breeze773** [rajdeut/terraform-aws-nightscout#3]
Hello,
Thanks for this code. I now my way around aws and terraform well enough to run things, but I've been getting this error
`Error: error creating S3 bucket ACL for nightscout-codepipeline-******`
during `terraform apply`. I was looking through the code and was wondering if there are some required variables not set but so far no luck with adding the name of my git repo, which is the standard 'cgm-remote-monitor'
I'd appreciate any help.
Thanks

**Comment by dgrebb** [comment]
@Breeze773 I opened a PR for the fix — just ran into this exact scenario last week.

The relevant info is in PR #4. For now, you can add the below just under the [`aws_s3_bucket.codepipeline_bucket` resource in `./main.tf`](https://github.com/rajdeut/terraform-aws-nightscout/blob/main/main.tf#L20).

```hcl
resource "aws_s3_bucket_ownership_controls" "codepipeline_bucket_ownership" {
  bucket = aws_s3_bucket.codepipeline_bucket.id
  rule {
    object_ownership = "ObjectWriter"
  }
}
```

Happy holidays!

**Comment by Breeze773** [comment]
Thanks, @dgrebb That did the trick.
